### ISSUE TITLE
Instructor Feedback Week 3

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [RoderickMonforte/LibraryOfAlexandriaForMTG#1]
Great job with your problem statement. It sounds like you'll be solving an issue you and LOT of other folks have. Looking forward to seeing you build this out.

- [x] There's some reference to the trail reports in your list of technologies and flow - clean up for your application
- [x] What is your independent research topic? Be sure to list it for your list of technologies
- [x] Looks like there are some good apis to choose from, try a google search for "magic the gathering api"
- [x] Are all screens represented in screens.md? Add or delete a card?
- [x] What, if any, functionality is available to somebody who does not have an account/is not logged in?
- [x] Do the prices change regularly? I'm curious if it might make sense to get the price from a service realtime rather than storing it? Or perhaps a batch update of prices? Or?
- [x] Will the application have an administrator role at all?
- [x] Project plan - clean up for your application. Consider the project requirements/deliverables and the course calendar to understand when topics will be introduced and when they might be implemented in your project.
- [x] Check formatting of the time log - the 1/28 entry is wrapping funny.

**Comment by RoderickMonforte** [comment]
for "Are all screens represented in screens.md? Add or delete a card? " - i was hoping that after hitting update that I can make that row editable and the user can enter the new values. I think I have seen that that is possible. Can data tables act as forms too? Another version I saw was that a space opens up between the row that is to be edited and the row after that and in the space is the form you can enter the updated values that you can hit a button save. I might be shooting myself if I can't do it. In that case I will create an independent Add/Update form.

for "What, if any, functionality is available to somebody who does not have an account/is not logged in?" It will be none for now. You cannot view other peoples collection or cards. If I have time I can have a brag page showing statistics on number of users, collection, cards and price currently being serviced by the application as a way of showing it works.

for "Do the prices change regularly? I'm curious if it might make sense to get the price from a service realtime rather than storing it? Or perhaps a batch update of prices? Or?" The one service I saw that is free encourages to pull all prices once and cache it. I do not know how that works but I am hoping we will discuss them. 

for "Will the application have an administrator role at all?" Right now I am thinking that it is up to the user to maintain their stuff. I could see in the future that an admin role can be added to clean up abandoned collections or user account but that I can argue for a batch process too.
